[System]
Numato1_Name = Relay_Board_DUT1
Numato1_Port= COM8
Numato2_Name = Relay_Board_DUT2
Numato2_Port = COM9
Programator1_Name = Programator_DUT1
Programator1_Port = COM3
Programator2_Name = Programator_DUT2
Programator2_Port = COM10
Printer = COM5
RS485_Port1_Port = COM11
RS485_Port2_Port = COM12
RS485_Port3_Port = COM13
RS485_Port4_Port = COM14
RS485_Port1_Name = RS485_Port1
RS485_Port2_Name = RS485_Port2
RS485_Port3_Name = RS485_Port3
RS485_Port4_Name = RS485_Port4
DMM_Address = 192.168.100.10
DMM_Name = DMM
Rigol1_Address = 192.168.100.11
Rigol1_Name = Rigol1
Rigol2_Address = 192.168.100.12
Rigol2_Name = Rigol2
Scanner1 = "COM17"
Scanner2 = "COM18"
[Cassete_Coding]
Code_327-LEPL-104-M-a = 1
Code_340-LEPL-102-A-e = 2
Code_340-LEPL-103-A-a = 4
[Label]
Software_Version_327-LEPL-104-M-a = "TS002AV110"
Software_Version_340-LEPL-102-A-e = "200SWAZ004I"
Software_Version_340-LEPL-103-A-a = "200SWAZ004I"
Hardware_Version_327-LEPL-104-M-a = "BL001BV105"
Hardware_Version_340-LEPL-102-A-e = "V108"
Hardware_Version_340-LEPL-103-A-a = "V108"
[Programming]
File_327-LEPL-104-M-a = "327-LEPL-104-M-a___200-SWTS-002-A-V110_b32___200-SWBL-001-B-V105_02.hex"
File_340-LEPL-102-A-e = "200-SWAZ-004-I-V108.hex"
File_340-LEPL-103-A-a = "200-SWAZ-004-I-V108.hex"
Family_327-LEPL-104-M-a = "P24EP128GP206"
Family_340-LEPL-102-A-e = "P16F882"
Family_340-LEPL-103-A-a = "P16F882"
## Relay numbers are currently set in groups that are based on variant and DUT position
##Relay numbers here start from 1, but are loaded in the VI with a -1 because 
## the relay numbers start from 0
[327_LEPL_104_M_Relays_DUT1]
PS1+_TP2  = 12
PS1-_TP1  = 13
RS_485_A+ = 19
RS_485_B- = 20
DMM_GND_TP1 = 21 
DMM_TP7 = 24
DMM_TP8 = 25
DMM_TP9 = 26
DMM_TP15 = 27 
DMM_TP3 = 22
DMM_TP4 = 23
Positive_Half_TP3 = 7
Negative_Half_TP3 = 8
Solid_shaft_TP3 = 6
AC_GND_TP1 = 9
Programator_VDD_TP15 = 2
Programator_GND_TP17 = 3
Programator_PGC_TP16 = 5
Programator_PGD_TP14 = 4
Programator_MCLR_TP12 = 1
PS2+_TP3 = 14
PS2-_TP1 = 15
##Relay numbers here start from 1, but are loaded in the VI with a -1 because 
## the relay numbers start from 0
[327_LEPL_104_M_Relays_DUT2]
PS1+_TP2  = 12
PS1-_TP1  = 13
RS_485_A+ = 19
RS_485_B- = 20
DMM_GND_TP1 = 21 
DMM_TP7 = 24
DMM_TP8 = 25
DMM_TP9 = 26
DMM_TP15 = 27 
DMM_TP3 = 22
DMM_TP4 = 23
Positive_Half_TP3 = 7
Negative_Half_TP3 = 8
Solid_shaft_TP3 = 6
AC_GND_TP1 = 9
Programator_VDD_TP15 = 2
Programator_GND_TP17 = 3
Programator_PGC_TP16 = 5
Programator_PGD_TP14 = 4
Programator_MCLR_TP12 = 1
PS2+_TP3 = 14
PS2-_TP1 = 15
##Relay numbers here start from 1, but are loaded in the VI with a -1 because 
## the relay numbers start from 0
[340_LEPL_102_A_Relays_DUT1]
24AC_TP2  = 6
24AC_GND  = 9
24AC_GND_TP1  = 23
24AC_GND_DMM_I  = 24
DMM_HI_TP2 = 25 
DMM_GND_TP1 = 21 
DMM_TP4 = 26
DMM_TP5 = 27
DMM_TP13 = 30
DMM_TP14 = 31 
DMM_GND_TP10 = 22
DMM_TP11 = 29
Programator_VDD_TP11 = 2
Programator_GND_TP10 = 3
Programator_PGC_TP8 = 5
Programator_PGD_TP9 = 4
Programator_MCLR_TP12 = 1
TP10_120Ohm_TP4 = 28
Thermal_Board_Switch = 17
LED_Resistance_DMM_HI = 32
Load_Brake = 16
X3_Pad = 18
##Relay numbers here start from 1, but are loaded in the VI with a -1 because 
## the relay numbers start from 0
[340_LEPL_102_A_Relays_DUT2]
24AC_TP2  = 6
24AC_GND  = 9
24AC_GND_TP1  = 23
24AC_GND_DMM_I  = 24
DMM_HI_TP2 = 25 
DMM_GND_TP1 = 21 
DMM_TP4 = 26
DMM_TP5 = 27
DMM_TP13 = 30
DMM_TP14 = 31 
DMM_GND_TP10 = 22
DMM_TP11 = 29
Programator_VDD_TP11 = 2
Programator_GND_TP10 = 3
Programator_PGC_TP8 = 5
Programator_PGD_TP9 = 4
Programator_MCLR_TP12 = 1
TP10_120Ohm_TP4 = 28
Thermal_Board_Switch = 17
LED_Resistance_DMM_HI = 32
Load_Brake = 16
X3_Pad = 18
##Relay numbers here start from 1, but are loaded in the VI with a -1 because 
## the relay numbers start from 0
[340_LEPL_103_A_Relays_DUT1]
230AC_TP2  = 10
230AC_GND  = 11
230AC_GND_TP1  = 23
230AC_GND_DMM_I  = 24
DMM_HI_TP2 = 25 
DMM_GND_TP1 = 21 
DMM_TP4 = 26
DMM_TP5 = 27
DMM_TP13 = 30
DMM_TP14 = 31 
DMM_GND_TP10 = 22
DMM_TP11 = 29
Programator_VDD_TP11 = 2
Programator_GND_TP10 = 3
Programator_PGC_TP8 = 5
Programator_PGD_TP9 = 4
Programator_MCLR_TP12 = 1
TP10_120Ohm_TP4 = 28
Thermal_Board_Switch = 17
LED_Resistance_DMM_HI = 32
Load_Brake = 16
X3_Pad = 18
##Relay numbers here start from 1, but are loaded in the VI with a -1 because 
## the relay numbers start from 0
[340_LEPL_103_A_Relays_DUT2]
230AC_TP2  = 10
230AC_GND  = 11
230AC_GND_TP1  = 23
230AC_GND_DMM_I  = 24
DMM_HI_TP2 = 25 
DMM_GND_TP1 = 21 
DMM_TP4 = 26
DMM_TP5 = 27
DMM_TP13 = 30
DMM_TP14 = 31 
DMM_GND_TP10 = 22
DMM_TP11 = 29
Programator_VDD_TP11 = 2
Programator_GND_TP10 = 3
Programator_PGC_TP8 = 5
Programator_PGD_TP9 = 4
Programator_MCLR_TP12 = 1
TP10_120Ohm_TP4 = 28
Thermal_Board_Switch = 17
LED_Resistance_DMM_HI = 32
Load_Brake = 16
X3_Pad = 18
##DI ports are separated to port 0 and port1. The values are from 1 but in VI are loaded as -1
## they are loaded like that to start from 0 value as the bits do
[DI_Port0]
DUT1_Encoder_A = 1
DUT1_Encoder_B = 2
DUT2_Encoder_A = 3
DUT2_Encoder_B = 4
DUT1_LED_Detection = 5
DUT2_LED_Detection = 6
DUT1_Present = 7
DUT2_Present = 8
[DI_Port1]
First_Safety_Relay = 1
Second_Safety_Relay = 2
Cassette_Code_Byte0 = 3
Cassette_Code_Byte1 = 4
Cassette_Code_Byte2 = 5
Cassette_Code_Byte3 = 6
Fixture_Closed = 7
Spare2 = 8
##Currently there is only port 0 for DO. The COM1 is not wired, so keep it in mind if number of added
## outputs exceed these 8 that are available
## here are values from 1 but they are saved from 0
[DO_Port0]
Emergency_stop_light = 1
DUT1_Contactor_coil_230VAC = 2
DUT2_Contactor_coil_230VAC = 3
Fixture_Lock = 4
Spare1 = 5
Spare2 = 6
Spare3 = 7
Spare4 = 8